package jokrey.utililities.swing.text_editor.example;

import jokrey.utililities.swing.text_editor.JPC_Connector;
import jokrey.utililities.swing.text_editor.ui.JPCSimpleWrappingTextEditor;
import jokrey.utililities.swing.text_editor.ui.core.JPC_Scroller;
import jokrey.utililities.swing.text_editor.text_storage.ContentEditor;
import jokrey.utililities.swing.text_editor.text_storage.WrappingContentEditor;
import jokrey.utililities.swing.text_editor.user_input.ContextFunctionalityLibrary;

import java.awt.*;

public class WrappingScrollingTextDisplay_Example {
    public static void main(String[] args) {
        JPCSimpleWrappingTextEditor textDisplay = new JPCSimpleWrappingTextEditor() {
            @Override public ContentEditor createContentEditor(JPC_Connector c) {
                return new WrappingContentEditor(c) {
                    @Override public boolean isSelectionEnabled() {
                        return true;//ok, because copying out is disabled, by not adding the context function and DND is disabled below.
                    }
                    @Override public boolean isDragAndDropEnabled() {
                        return false;
                    }
                };
            }
        };
        textDisplay.setEditable(false);

        JPC_Scroller scroller = new JPC_Scroller(textDisplay);

        textDisplay.clearContextActions();
        textDisplay.addContextAction(ContextFunctionalityLibrary.getFunctionality_TOGGLE_WRAPPING(textDisplay));
        textDisplay.addContextAction(ContextFunctionalityLibrary.getFunctionality_FIND(textDisplay, textDisplay.getInputHandler()));
        textDisplay.addContextAction(ContextFunctionalityLibrary.getFunctionality_FONT_CYCLE_STYLE(textDisplay));
        textDisplay.addContextAction(ContextFunctionalityLibrary.getFunctionality_CYCLE_FG_COLOR(textDisplay));
        textDisplay.addContextAction(ContextFunctionalityLibrary.getFunctionality_CYCLE_BG_COLOR(textDisplay));
        textDisplay.addContextAction(ContextFunctionalityLibrary.getFunctionality_FONT_SIZE_UP(textDisplay));
        textDisplay.addContextAction(ContextFunctionalityLibrary.getFunctionality_FONT_SIZE_DOWN(textDisplay));
        textDisplay.addContextAction(ContextFunctionalityLibrary.getFunctionality_PAGE_UP(scroller, textDisplay));
        textDisplay.addContextAction(ContextFunctionalityLibrary.getFunctionality_PAGE_DOWN(scroller, textDisplay));


        textDisplay.setText(getText());

        textDisplay.setFont(new Font("Arial", Font.BOLD, 13));

        FrameStarter.start("JPC Editor - this edition wraps, scrolls and does not allow the text to be edited or extracted", scroller);
    }




    static String getText() {
        return "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse vitae fringilla orci. Nullam sit amet lacus vel nulla ornare dictum dignissim nec mi. Proin venenatis aliquam sapien, at iaculis turpis aliquet sit amet. Pellentesque dui risus, viverra eu rutrum vel, viverra eu ex. Nullam scelerisque mattis ipsum, sit amet ultricies lorem maximus non. Nullam a gravida nisi, sed dictum justo. Curabitur quis fermentum augue, quis fringilla urna. Curabitur bibendum mollis risus, vitae laoreet odio sollicitudin ut. Pellentesque diam ligula, auctor at bibendum fringilla, aliquet quis quam.\n" +
                "\n" +
                "Suspendisse hendrerit nec eros non lacinia. In scelerisque lacus volutpat, finibus enim sed, ullamcorper risus. Fusce lacus orci, auctor eu odio quis, vulputate consectetur est. Quisque et efficitur tortor. Vivamus sollicitudin eget quam id vestibulum. Aliquam semper ex nec turpis ullamcorper, ac ultricies elit faucibus. Vestibulum lectus tellus, pulvinar a justo quis, gravida laoreet ante. Aliquam sagittis egestas aliquet. Cras volutpat fermentum lacinia. Morbi convallis convallis justo, quis feugiat libero faucibus in.\n" +
                "\n" +
                "Curabitur ullamcorper tempus libero, sed tincidunt mauris rhoncus sit amet. Phasellus vel mi ac libero aliquam varius scelerisque at eros. Cras vitae dictum enim, nec scelerisque felis. Nullam maximus eget risus sit amet pellentesque. Morbi congue scelerisque augue et interdum. Sed lacinia vitae nunc quis suscipit. Suspendisse id quam eleifend, bibendum turpis tincidunt, auctor sem. Nunc aliquet semper fermentum.\n" +
                "\n" +
                "Duis mollis, enim ut pretium finibus, est lorem vehicula arcu, vitae euismod massa massa ac nisi. Etiam pulvinar suscipit ex, eget congue magna vehicula quis. Morbi fermentum nulla et erat tristique, ut bibendum odio imperdiet. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque ut interdum leo. Suspendisse a faucibus elit. Nam auctor malesuada nisi, vel ultrices quam ultrices vitae. Vivamus consequat, sapien ac dignissim placerat, leo arcu luctus sapien, vitae iaculis mauris lacus nec tellus. Quisque pulvinar ullamcorper velit, elementum finibus neque. Quisque vel hendrerit enim. Aenean vel varius libero.\n" +
                "\n" +
                "Interdum et malesuada fames ac ante ipsum primis in faucibus. Nullam lacinia leo eu nisl vestibulum eleifend. Integer nec malesuada neque, quis viverra nisl. In faucibus enim ac nisl faucibus, non cursus nunc dapibus. In erat erat, consequat efficitur suscipit et, mattis et diam. Vestibulum eros dui, dapibus ut nisl vitae, imperdiet tincidunt enim. Duis vestibulum justo nec elit cursus, sed tincidunt elit lobortis. Sed lobortis metus non lorem luctus suscipit. Donec et tincidunt felis. Curabitur vel eros sed nibh ornare lacinia. Nulla id vestibulum magna. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Duis vehicula suscipit odio, nec accumsan risus. Nam fringilla vel diam vel rhoncus. Nulla bibendum ex nunc, ut laoreet nisi ultrices eu.\n" +
                "\n" +
                "Ut sed\t efficitur augue. Donec vel justo libero. In augue nisi, eleifend eu rutrum ut, gravida sed odio. Proin bibendum dolor ligula. Donec porta congue arcu, ac vehicula massa ornare ut. Praesent consectetur ligula id quam auctor, non placerat justo pharetra. Aliquam sed ipsum maximus, auctor turpis vel, aliquet augue. Mauris lobortis nunc urna, et pharetra neque congue a. Nam vulputate, felis in iaculis sodales, massa orci blandit lorem, nec cursus velit arcu eu ligula. Donec vulputate ut ex ac lacinia. Nullam efficitur orci in lectus tempor, id mollis mauris placerat. Praesent id vehicula massa. Sed tristique lacus sed commodo dapibus.\n" +
                "\n" +
                "Morbi\t non vulputate purus, at viverra elit. Donec ipsum risus, tempor in pretium ut, facilisis tincidunt ex. Nulla vitae nisi aliquet, accumsan lectus quis, rhoncus orci. Ut in massa mattis, rhoncus libero vel, congue erat. Pellentesque pulvinar id nulla id facilisis. Vivamus eu ex ligula. Donec condimentum posuere tellus, sit amet placerat sem viverra at. Mauris eget leo non tortor sagittis ultricies.\n" +
                "\n" +
                "Pellentesque viverra dui sed sollicitudin imperdiet. Donec arcu ex, ullamcorper ut accumsan sed, malesuada vitae libero. Curabitur sed velit quis ante condimentum aliquam. Curabitur rutrum non ante vel vehicula. Suspendisse vel enim sapien. Ut ut ligula eget leo semper dignissim vitae aliquam nibh. Nam vestibulum mauris metus, sed dictum est eleifend nec. Fusce sit amet leo efficitur, viverra erat in, consectetur massa. Praesent ut nunc eu dui ultrices venenatis. Etiam in ornare dolor. Nulla facilisi. Interdum et malesuada fames ac ante ipsum primis in faucibus. Vestibulum in dignissim nibh. In efficitur congue diam, nec efficitur ex ultrices pharetra. Vivamus a mauris a purus gravida interdum nec sed enim.\n" +
                "\n" +
                "Phasellus blandit ex ut egestas suscipit. Aenean ante purus, feugiat eu porttitor sit amet, maximus vel nisi. Pellentesque ante libero, lacinia non massa at, vehicula ullamcorper quam. Vivamus vulputate, diam in tincidunt euismod, elit magna tincidunt justo, in congue risus nunc sit amet elit. Aenean magna elit, dignissim at egestas at, rhoncus id lacus. Vivamus rhoncus mauris ac tortor volutpat, sit amet scelerisque lacus dapibus. Quisque tincidunt turpis non nisi facilisis, rutrum commodo enim sagittis. Proin tincidunt, leo in imperdiet tristique, justo augue congue dolor, ac pulvinar felis libero in eros. Praesent id nulla mi. Mauris eget justo varius, venenatis dui nec, varius arcu. Praesent vitae ante at sapien pharetra rhoncus. Integer eget varius lectus. Aliquam convallis tempus velit ut suscipit. Fusce mollis tincidunt erat, at fermentum ipsum mattis sit amet.\n" +
                "\n" +
                "Phasellus sagittis, augue eget egestas elementum, massa ligula accumsan ante, ac elementum est urna ut lacus. Vivamus risus nunc, varius sed lectus at, gravida lobortis elit. Sed rutrum dui ut nulla efficitur tempus. Sed ut velit arcu. Maecenas efficitur nunc at molestie aliquam. Donec eleifend et massa accumsan bibendum. Mauris lectus libero, mattis id fringilla ut, aliquam at lorem. Pellentesque ultricies convallis odio, in aliquam massa malesuada quis. Fusce eleifend nec neque eu dignissim. Vivamus id turpis quis est placerat finibus.\n" +
                "\n" +
                "Ut convallis placerat purus sed euismod. Integer vulputate, nunc interdum malesuada commodo, lacus enim molestie massa, ac fermentum ante nisl eu sem. Etiam tempor tincidunt velit quis aliquam. Ut sed lorem et risus euismod tristique non ut lorem. Praesent id mattis tortor. Quisque eleifend, ipsum in molestie scelerisque, dui lacus tincidunt ligula, nec malesuada magna tortor ac neque. Nullam at nunc luctus, laoreet mi vitae, rhoncus metus. Quisque hendrerit mattis libero, quis euismod mi sodales sed. Phasellus faucibus ipsum suscipit scelerisque gravida. Nullam sed pretium ipsum.\n" +
                "\n" +
                "Duis non sodales risus. In hac habitasse platea dictumst. Phasellus hendrerit quam vel tincidunt eleifend. Curabitur pharetra vestibulum sapien id bibendum. Nullam id suscipit sem. Morbi accumsan consectetur sodales. Aenean a eros et felis consectetur pellentesque in sit amet nunc. Praesent sit amet quam sollicitudin, gravida sem eu, pretium est. Nullam a ultrices purus. Sed condimentum leo ac lobortis cursus. Maecenas varius scelerisque dui, vel gravida tortor consequat id. Aenean pellentesque ligula vestibulum ligula pretium, sit amet feugiat libero aliquam. In in rhoncus eros. Donec nec nisi magna. Duis vitae urna eget nulla facilisis iaculis sed non purus.\n" +
                "\n" +
                "Suspendisse ante nisi, dictum eu quam eget, ullamcorper imperdiet magna. Sed sit amet ultricies massa. Nunc consectetur enim mi, sed pharetra eros dignissim a. Phasellus at tortor nunc. Etiam non turpis quis lorem ultricies ultrices in ac leo. Nullam tempus dui non malesuada pellentesque. Vivamus eget auctor tellus, in tincidunt felis. Proin ullamcorper ipsum purus, eget varius sapien interdum ut. Vivamus venenatis turpis et dui mattis varius.\n" +
                "\n" +
                "Nulla varius non ipsum in condimentum. Vivamus ornare pulvinar metus eu auctor. Vestibulum in volutpat velit. Cras pulvinar in arcu a lacinia. Curabitur maximus rhoncus felis vitae ornare. Quisque faucibus accumsan eros id pretium. Ut iaculis purus id feugiat semper. Sed ut porttitor diam. Sed quis lobortis dolor. Suspendisse dignissim feugiat nulla.\n" +
                "\n" +
                "Fusce at congue tortor. Aliquam at dignissim lacus, id hendrerit neque. Donec eros massa, finibus a convallis ut, posuere in arcu. Pellentesque vitae euismod felis, vel elementum ex. Donec tristique erat sit amet elit malesuada hendrerit. Nunc quam elit, vulputate a erat blandit, rutrum blandit est. Ut rhoncus enim non bibendum ornare. Phasellus eros lectus, sagittis vitae erat ac, aliquam hendrerit ex. Cras id leo semper, semper nibh id, blandit neque. Pellentesque tincidunt blandit tortor vel facilisis. Vivamus tempus nulla at nulla malesuada dignissim.\n" +
                "\n" +
                "Vivamus sagittis orci a sem vehicula, mollis euismod massa dapibus. Fusce bibendum aliquam felis. Integer at venenatis ligula. Duis fringilla pulvinar sapien eu aliquet. Sed id condimentum turpis. Cras nibh felis, blandit fringilla vulputate a, accumsan quis turpis. Nam ut sollicitudin ex, eget lobortis nibh. Vestibulum non efficitur orci. Quisque a venenatis ante, non tristique quam. Nam in aliquam mi. Curabitur varius libero a libero dictum, in efficitur risus cursus. Vestibulum lacus nibh, blandit vel pulvinar hendrerit, rutrum iaculis ligula.\n" +
                "\n" +
                "Maecenas tellus nisl, commodo eget bibendum sed, aliquet vitae nibh. Etiam bibendum ex nec fringilla dapibus. Nullam cursus eget dui at dapibus. Fusce a quam at diam tempor blandit ullamcorper eget mauris. Sed convallis tempus lacus vel feugiat. Sed porttitor est nulla, eget dictum turpis ornare quis. Nulla aliquam ipsum neque, quis pulvinar lacus tincidunt sit amet. Ut iaculis nulla eu vulputate venenatis. Sed a neque dolor. Cras molestie vitae nisi eget dignissim. Etiam finibus blandit placerat. Phasellus at arcu sed diam lacinia scelerisque. Vivamus metus libero, sodales vitae massa et, convallis mattis sem. Donec sagittis dolor eu pellentesque tristique. Mauris et est dapibus, ultrices massa quis, aliquet ante.\n" +
                "\n" +
                "Etiam tellus diam, iaculis ut ex vitae, volutpat faucibus libero. Sed facilisis urna in risus condimentum, quis tincidunt mauris volutpat. Phasellus dictum bibendum enim, non bibendum nibh bibendum sed. In hac habitasse platea dictumst. Aenean blandit placerat sollicitudin. Nunc fermentum auctor massa, vel auctor erat pretium id. Maecenas varius non metus eget gravida. Cras porttitor pharetra efficitur. Fusce pulvinar bibendum mauris id maximus.\n" +
                "\n" +
                "Mauris porttitor facilisis risus, a consectetur justo suscipit sit amet. Nam placerat fermentum massa, eget ullamcorper leo sagittis sagittis. Praesent convallis, ligula in lobortis dictum, felis orci tincidunt eros, at malesuada nunc nisi condimentum ipsum. Ut vulputate, mauris quis ultricies ornare, magna urna sollicitudin sem, sit amet lacinia dolor ante et massa. Pellentesque consectetur tortor sed ligula euismod ullamcorper. Phasellus sollicitudin mauris quis vehicula ornare. Mauris sed eros nisi. Sed congue, diam in commodo rutrum, risus neque sagittis lacus, sed pellentesque leo nibh ac diam. Nulla convallis tortor eget imperdiet ultrices. Integer sed rutrum nisi. Vestibulum dui lorem, porta sed placerat sit amet, facilisis at nibh.\n" +
                "\n" +
                "Praesent id laoreet leo. Aenean sit amet tincidunt arcu. Cras sollicitudin velit vitae risus interdum cursus. Aenean eros turpis, ultrices vitae nibh eget, cursus convallis nunc. Nam vehicula libero nec finibus vulputate. Etiam eu semper velit. Maecenas mattis tortor nec nunc ullamcorper, quis rutrum nisi rhoncus. Integer blandit ultrices dui quis elementum. Duis sodales nibh vel felis dictum tincidunt. Sed non dictum enim. Integer faucibus venenatis semper. Etiam felis magna, iaculis sed risus quis, lobortis consequat lectus.\n" +
                "\n" +
                "Suspendisse elementum pulvinar metus, et vestibulum diam laoreet vitae. Phasellus enim velit, hendrerit ac suscipit vitae, consequat in velit. Suspendisse fringilla dolor quis interdum volutpat. Aliquam mauris ex, aliquam id varius ut, maximus ut sem. Mauris eget neque volutpat orci consequat fermentum. Aliquam ullamcorper risus at tortor interdum pulvinar. Curabitur eu ante nec purus finibus accumsan aliquam vel urna. Vivamus consequat eget lacus et sagittis.\n" +
                "\n" +
                "Proin malesuada, augue et varius faucibus, lectus metus aliquet purus, nec porttitor magna tellus vitae mauris. Proin molestie, mi quis sollicitudin cursus, lectus elit convallis felis, id tristique magna nulla vel orci. Cras quis hendrerit est. Aenean dignissim arcu et turpis luctus porta. Donec porta laoreet tempor. Mauris pretium, orci vel laoreet dignissim, ante ligula congue magna, vitae tincidunt purus purus quis tortor. Sed eget lobortis ligula. Aenean consequat, leo non viverra egestas, sapien eros scelerisque leo, a suscipit lectus purus nec nisi. Sed id odio nisi. Suspendisse tempus tincidunt libero, eget rutrum purus lobortis nec. In sit amet turpis vel metus lacinia ultrices sed ut nunc. Phasellus convallis ligula eget congue commodo. Sed sed finibus ligula, a condimentum odio. Nullam aliquet fringilla nisl eget lacinia.\n" +
                "\n" +
                "Proin aliquet nunc viverra, accumsan velit eget, aliquet nisl. Donec consectetur ac leo in elementum. Integer sem justo, aliquet eu egestas sit amet, porta sed tortor. Suspendisse potenti. Nullam auctor quis nisi in consectetur. Aliquam ac tempor mi, et lobortis mi. Aliquam condimentum dui quis mollis auctor. Nam quis pretium mauris. Aenean massa quam, blandit et arcu a, porttitor molestie nulla. Aenean malesuada efficitur nunc feugiat eleifend. Nulla luctus accumsan tempor.\n" +
                "\n" +
                "Nunc volutpat rhoncus malesuada. Etiam bibendum neque lectus, eu fermentum odio iaculis non. Sed tristique sem id justo tincidunt ultrices. Nullam congue enim sed malesuada vulputate. Curabitur tincidunt convallis fermentum. Suspendisse efficitur bibendum ultrices. Sed sed risus ultricies nisl varius pretium eu sed nisl. Aliquam commodo nisl purus, nec sagittis velit tempus ac. Fusce dolor arcu, tempor nec purus vel, accumsan fermentum mauris. Curabitur a purus elementum, interdum sem eget, egestas eros. Sed turpis enim, ullamcorper nec viverra eget, aliquet eget risus. In mi odio, sodales ut elit eu, tincidunt aliquet nisl. Duis non volutpat mi.\n" +
                "\n" +
                "Sed magna est, tempus eu convallis at, egestas in odio. Fusce erat metus, viverra eu neque nec, condimentum venenatis quam. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Aliquam consequat arcu massa, eu auctor dolor pretium non. Nunc elementum risus ut mi vehicula, vitae maximus nisi tincidunt. Integer porta ligula lorem, et vulputate nibh luctus vel. Etiam turpis turpis, varius a pellentesque id, vulputate id dui. Donec sollicitudin malesuada volutpat. Duis venenatis nisi eros, sed tempor libero luctus ac. Cras faucibus metus purus, non luctus purus dignissim vitae. Etiam ullamcorper leo vitae scelerisque consequat. Pellentesque accumsan elit eget gravida egestas. In dignissim euismod velit, a tincidunt metus vestibulum nec. Praesent volutpat est vitae quam rhoncus feugiat.\n" +
                "\n" +
                "Maecenas vel lorem mollis, porta dolor id, dignissim purus. Curabitur posuere, erat laoreet pellentesque ornare, est purus commodo felis, sit amet vulputate arcu dolor ut leo. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Proin ac velit purus. Duis finibus lorem in felis gravida venenatis. Nulla facilisi. Nullam luctus leo ut est volutpat, eget aliquam leo sodales. Fusce non eros elit. Ut condimentum molestie felis, in pretium libero suscipit ut. Vivamus dolor mauris, interdum ut lacinia id, cursus vel metus. Sed sagittis turpis ut lectus vehicula, sit amet ullamcorper mauris sollicitudin. Sed vehicula sapien eget sem posuere ullamcorper. Phasellus scelerisque leo at viverra posuere. Proin ac rhoncus lacus. Nam et sodales massa.\n" +
                "\n" +
                "Sed in dapibus dolor. Curabitur eu nulla cursus, volutpat nunc vitae, finibus turpis. Vivamus in risus et quam volutpat tempus. Phasellus vestibulum pharetra pretium. Sed non odio eleifend ex finibus pulvinar eu sit amet nibh. Nunc gravida lorem tellus, ut lobortis urna dictum ac. Ut sit amet ultrices neque. Praesent dapibus ipsum sit amet malesuada sodales.\n" +
                "\n" +
                "Vivamus sollicitudin id augue ac cursus. Aenean eleifend sollicitudin augue a ornare. Sed vel mauris tellus. Aliquam velit ligula, mollis non pellentesque ut, rhoncus sed orci. Mauris iaculis ipsum at orci dignissim, eu posuere metus suscipit. Etiam ultricies, sapien a faucibus suscipit, felis sapien rhoncus orci, a varius risus ligula non nisi. Donec vehicula eget tortor quis rutrum. Ut bibendum ut mauris semper dictum. Integer dapibus vitae urna in luctus.\n" +
                "\n" +
                "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Suspendisse commodo, nisl a sagittis placerat, turpis arcu volutpat nulla, sit amet imperdiet elit magna vel est. Suspendisse diam tellus, venenatis eu elit et, tincidunt iaculis leo. Donec pellentesque vestibulum lacinia. Mauris quis vestibulum sem. Ut et leo at lacus maximus blandit. Donec convallis tellus et risus mollis placerat. Aenean congue non arcu vel tincidunt. Vivamus ullamcorper accumsan iaculis. Quisque mollis, justo non tristique scelerisque, magna ipsum tristique turpis, ut lacinia ante felis mollis enim. Integer sodales, mauris ut lacinia fermentum, erat ante tincidunt lorem, at viverra erat quam imperdiet massa. In ut laoreet lacus. Curabitur tempor urna sed tortor euismod luctus. Quisque congue placerat velit, ut iaculis ipsum congue quis. Sed tempor ultrices posuere.\n" +
                "\n" +
                "Donec maximus ante eget lacus vulputate fermentum. Vivamus lobortis ut lectus eu bibendum. Curabitur malesuada nibh risus, a pulvinar nisl vehicula eu. In blandit volutpat neque, eleifend rutrum sem tempor et. Duis sollicitudin, odio et volutpat dapibus, tellus risus tempor leo, id laoreet lorem enim in ex. Proin vitae consequat ipsum. Integer pretium consequat ligula id malesuada. Donec gravida mauris non sapien elementum, at auctor felis imperdiet. Aliquam erat volutpat.\n" +
                "\n" +
                "In quis diam vitae nibh pulvinar faucibus. Suspendisse pulvinar facilisis felis ac bibendum. Integer purus massa, ornare non turpis ut, porta feugiat nisi. Aenean sagittis ultrices augue. Praesent ac augue quis nunc elementum fermentum eu quis elit. Vestibulum a laoreet quam. Mauris non ante quis augue ornare hendrerit. Pellentesque rutrum pellentesque blandit. Aenean nec sem eget nisi pulvinar commodo. Cras varius diam mi. Mauris a imperdiet massa. Phasellus aliquam libero in lorem posuere, non convallis enim maximus. Aliquam erat mauris, eleifend at tortor eget, tincidunt sodales lorem. Etiam tellus massa, placerat eu elit at, feugiat fermentum odio.\n" +
                "\n" +
                "Morbi euismod ipsum id urna commodo pharetra. Nullam lorem lorem, lobortis id auctor sit amet, pharetra et mi. Donec velit metus, vehicula non sem at, pharetra volutpat nunc. In hac habitasse platea dictumst. Etiam vestibulum vel nisl id mollis. In hac habitasse platea dictumst. Maecenas lacinia quis diam vitae pharetra.\n" +
                "\n" +
                "Nulla lacinia arcu et leo mattis, ac bibendum orci aliquet. Phasellus ac egestas lacus. Sed arcu nibh, blandit eu ultricies vitae, pharetra sed leo. Nam magna nisi, vulputate non tincidunt ac, volutpat tempus sem. Sed a imperdiet purus, eget ultricies nisi. Donec ullamcorper augue mi, tincidunt accumsan velit consectetur sit amet. Nulla a nunc elementum, pulvinar sapien et, convallis elit. Morbi faucibus tellus at metus ultricies, ut vestibulum felis porta. Nunc et lacinia lorem. In purus libero, tempus sed leo eget, elementum porttitor libero. Praesent dignissim, augue at viverra posuere, dui purus viverra dolor, sed lobortis urna erat vitae lectus. Nulla enim metus, maximus eget justo et, mollis aliquam metus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Vivamus non imperdiet ex, non rutrum elit. Nullam auctor lorem felis, id condimentum massa fermentum eu.\n" +
                "\n" +
                "Quisque eget vestibulum erat. Nunc sit amet placerat felis, laoreet accumsan lectus. Vestibulum non neque dapibus, vehicula eros eleifend, ornare ligula. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Pellentesque aliquam mauris ut pharetra vehicula. Donec eget dolor ultricies, ornare erat in, egestas augue. Morbi dignissim diam id est cursus, vitae porttitor ante aliquet. Vestibulum rhoncus vitae leo eu tincidunt. Morbi sit amet ornare urna. Curabitur maximus elementum leo, ac euismod dui sagittis non.\n" +
                "\n" +
                "Sed laoreet sagittis orci quis ullamcorper. Aenean euismod finibus nulla vel faucibus. Mauris ac est vitae urna placerat dapibus vel vitae tortor. In vitae felis hendrerit ligula mollis pretium. Etiam tempor ligula efficitur, interdum arcu id, consequat ante. Nunc consequat at velit nec dapibus. In eleifend mollis nisi, id egestas eros accumsan quis. Aliquam erat volutpat. Morbi ac nulla urna. Vestibulum ut tortor sed metus vestibulum euismod ut at eros. In hac habitasse platea dictumst.\n" +
                "\n" +
                "Mauris et vulputate lacus. Integer risus elit, ultrices vitae posuere vel, porttitor at velit. Maecenas fringilla quis dui elementum vestibulum. Nam nibh arcu, tempus et consectetur eget, rutrum nec orci. Morbi malesuada in neque ac blandit. Maecenas ullamcorper lacus ut ex lacinia euismod euismod in arcu. Praesent consectetur neque sit amet aliquet iaculis. Donec ut blandit eros. Nunc in elit eu arcu vehicula laoreet. Nulla cursus ipsum orci, id ornare ex aliquam non. Nullam in quam dui. Praesent viverra est non est elementum tristique et id sem.\n" +
                "\n" +
                "Sed ullamcorper nulla at arcu molestie laoreet. Sed convallis elit et rhoncus viverra. Etiam nec magna luctus, rutrum nunc eu, ultricies metus. Nam mollis dolor eget est aliquet vestibulum. Integer et sapien et metus efficitur sodales. Curabitur lacus lorem, placerat ac massa sit amet, pulvinar suscipit lacus. Vivamus vehicula tincidunt dolor, non porta mi aliquet sed.\n" +
                "\n" +
                "Nulla auctor est tortor. Nunc id ex purus. Aliquam id libero vel eros blandit venenatis ut sit amet arcu. Aenean quis urna ut arcu aliquet volutpat sit amet eu augue. Aliquam eget porttitor dolor, nec laoreet mi. In dignissim, ligula quis porta cursus, justo mi luctus quam, a tempor odio ipsum sed risus. Praesent semper at mi ut condimentum. Nullam quis lacinia massa. Proin auctor a ex a mattis. Aenean id urna a enim maximus lacinia. Quisque quis sagittis augue, ac auctor urna.\n" +
                "\n" +
                "Cras et fringilla nulla. In quis sem vel massa laoreet posuere in ut orci. Duis feugiat, neque nec convallis tincidunt, lacus velit tincidunt libero, non vehicula leo velit aliquet sapien. Sed non dui nisl. Ut lacinia porta nibh et dapibus. Suspendisse semper nisi quis massa ultrices, eu laoreet ligula varius. Phasellus vel aliquet odio, a rutrum lorem. Nam ac est ligula. Phasellus eget mauris vitae diam lacinia gravida. Suspendisse tincidunt porttitor nisl id pharetra. Donec et leo quis eros posuere tempus. Vestibulum ut dui maximus, fringilla risus non, cursus odio. Duis finibus scelerisque elit vitae finibus. Etiam a velit neque. Nunc sodales volutpat diam non vehicula.\n" +
                "\n" +
                "Nulla in leo eget magna mollis ullamcorper. Donec lacinia ligula vitae maximus cursus. Ut aliquam turpis eu quam aliquet luctus. Nullam pulvinar purus at cursus tempus. Nulla eget justo dictum, convallis mi sed, tincidunt tortor. Donec non lacinia odio, vel malesuada ante. Ut ullamcorper id dui gravida pellentesque. Nam sodales urna sit amet turpis tincidunt iaculis. Duis pulvinar ligula id nibh tincidunt faucibus. Curabitur in commodo nisl, cursus sodales risus. Sed tempus tellus id leo convallis condimentum. Proin dolor libero, sagittis et euismod non, tempus at mauris. Vestibulum consequat iaculis tortor non rhoncus. Nunc et elit eros.\n" +
                "\n" +
                "Maecenas sodales enim ac diam aliquet tincidunt. In hac habitasse platea dictumst. Nullam iaculis ornare fermentum. Donec tincidunt, nulla eget tristique facilisis, quam nisl malesuada sapien, et egestas magna dui vel libero. Suspendisse potenti. Curabitur imperdiet leo ut mauris accumsan, eu elementum libero mattis. Vestibulum elementum nulla sit amet vehicula efficitur. Ut sodales suscipit massa sed pretium. Sed purus risus, vehicula volutpat efficitur non, mattis quis nunc. Nunc sagittis tellus at tristique blandit.\n" +
                "\n" +
                "Donec ornare convallis mi, id gravida diam dictum ac. Fusce viverra tellus eget dolor posuere ultricies. Donec at elit nunc. Duis vulputate elit augue, vitae efficitur lacus viverra accumsan. Maecenas tincidunt neque non lacus ullamcorper, in vehicula mi semper. Cras eu molestie diam. Quisque sodales lacus lacus, quis consequat elit ultricies a. Cras et eros imperdiet, vestibulum quam non, pretium ex. Morbi feugiat metus urna, ut tincidunt velit volutpat vitae. Pellentesque ac velit nec nisl imperdiet faucibus. Cras posuere gravida nunc, in placerat magna molestie sit amet. Morbi tincidunt, magna sed tristique luctus, neque nisi facilisis elit, a pulvinar ipsum augue sit amet lectus. Mauris ac ante urna. Donec posuere magna et lorem tristique tincidunt.\n" +
                "\n" +
                "In nunc odio, porttitor at gravida a, lobortis vel mauris. Suspendisse egestas diam orci, at tempus tellus ultricies id. Vivamus gravida sapien eu ultricies elementum. Ut consectetur est orci, nec viverra neque laoreet ac. Duis ex nunc, sodales sit amet vulputate ac, rutrum nec odio. Aenean vitae orci leo. Donec eu nibh non quam tincidunt semper in non ligula. Phasellus pulvinar metus enim, at volutpat turpis aliquet id. Integer eget leo sed lorem feugiat imperdiet quis ut mi. Praesent rhoncus quam ex, vitae congue ligula volutpat ut. Praesent molestie erat sed elit placerat fringilla. Fusce fringilla odio nec tortor scelerisque blandit. Ut tincidunt vitae mi pretium dictum. Mauris nulla tortor, lobortis et lorem convallis, egestas malesuada arcu. Nam vitae pellentesque velit, commodo luctus neque. Maecenas porta tincidunt dignissim.\n" +
                "\n" +
                "Phasellus dapibus dignissim purus in condimentum. In massa mi, eleifend tristique porta sed, dapibus non diam. Etiam in ultrices neque. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Cras nec enim augue. Sed et justo euismod, auctor eros vel, mattis purus. Integer ut eros in ex elementum interdum a a enim.\n" +
                "\n" +
                "Vestibulum ac arcu sit amet ante consectetur blandit at a magna. Curabitur quis lorem faucibus, aliquam mauris vitae, sodales ex. Suspendisse sed leo purus. Proin ullamcorper arcu in sem sodales, eget cursus nibh malesuada. Duis fermentum metus at nisl placerat, nec vulputate sem varius. Nam volutpat erat quis leo posuere mollis. Etiam enim diam, dictum eu tempor volutpat, feugiat a lorem. Mauris nunc urna, congue at auctor a, porta a augue. Vestibulum vestibulum venenatis odio. Sed hendrerit risus sit amet placerat hendrerit. Morbi ligula massa, consectetur eu pharetra id, convallis et lacus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Cras vulputate commodo magna sed viverra. Nunc nec lorem odio. Aliquam eget quam at augue consectetur vulputate.\n" +
                "\n" +
                "Quisque lobortis erat vel nulla consectetur, ac egestas massa feugiat. Nulla nec pellentesque felis. Pellentesque ornare iaculis purus sed iaculis. Mauris vehicula enim odio, sit amet iaculis augue eleifend eu. Mauris id mollis lacus, sed tristique dui. Nullam et lorem dignissim, volutpat lacus ut, dictum justo. Suspendisse lacinia vestibulum porta. Maecenas sit amet ultrices diam.\n" +
                "\n" +
                "Aenean vitae ultrices est. Quisque aliquet efficitur velit, vel elementum tellus laoreet at. Sed nisl neque, malesuada at facilisis vulputate, finibus placerat augue. Fusce suscipit fermentum commodo. Sed sed vestibulum erat. Nullam rutrum vitae mauris at varius. Suspendisse eu interdum lacus, ac malesuada neque. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aenean velit lacus, porta nec tincidunt et, ornare vitae nisl. Aenean consequat ultrices magna, tempor molestie diam gravida quis. Suspendisse ornare, ante ac elementum cursus, metus augue eleifend ex, in lacinia erat eros ac risus. In hac habitasse platea dictumst. Integer sagittis ornare nunc, cursus sodales mauris aliquam sit amet.\n" +
                "\n" +
                "Integer non ipsum ornare, dignissim lacus vel, scelerisque augue. Donec facilisis erat bibendum justo ullamcorper, sit amet imperdiet turpis mattis. Phasellus eget nibh justo. Quisque vel est ante. Proin sed magna lacus. Donec scelerisque interdum interdum. Proin ornare porta malesuada. Quisque non lectus mattis, placerat orci vitae, lobortis ipsum. Etiam fermentum ultrices arcu consectetur fringilla. Sed commodo tincidunt ligula eget dignissim. Etiam scelerisque eu quam vitae feugiat. Vestibulum ac placerat ligula. Aenean a metus augue.\n" +
                "\n" +
                "Sed venenatis viverra nunc. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Etiam accumsan vulputate ultricies. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aliquam cursus a lacus quis eleifend. Nam maximus risus convallis tellus commodo, nec varius tortor euismod. Quisque ut tincidunt nunc. Proin pharetra aliquet arcu quis cursus.\n" +
                "\n" +
                "Nulla eget consectetur nisl, at molestie velit. Aliquam dictum lectus non nibh luctus pulvinar. Integer bibendum nec ipsum quis vulputate. Maecenas nunc elit, fermentum non interdum elementum, congue at turpis. In id dui purus. Sed sit amet pharetra velit. Etiam a justo mattis, mattis nibh vel, faucibus nulla. Fusce interdum, risus a sodales cursus, ipsum felis placerat eros, ac commodo mauris lectus at nisl. Nullam eget nisi ut est hendrerit placerat at non libero. Vivamus ut tortor mi. Sed pretium, velit eu semper mattis, sapien nisi imperdiet neque, quis congue risus nisi ac sem. Etiam ac luctus dui, eu mollis lacus. Donec ut risus non purus hendrerit eleifend varius vel nibh. Mauris sodales tristique rutrum. Aenean eu nibh sem. Lorem ipsum dolor sit amet, consectetur adipiscing elit.\n" +
                "\n";
    }
}
